services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  prisma-migrate:
    build:
      context: .
      dockerfile: packages/prisma/Dockerfile.prisma
    volumes:
      - .:/app
      - /app/node_modules
      - prisma_generated:/app/packages/prisma/generated
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb?schema=public
    command: pnpm --filter=@glory-destiny-online-guide/prisma run migrate:dev --name init
    # 一次性任務，完成後退出

  prisma:
    build:
      context: .
      dockerfile: packages/prisma/Dockerfile.prisma
    volumes:
      - .:/app
      - /app/node_modules
      - prisma_generated:/app/packages/prisma/generated
    depends_on:
      prisma-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb?schema=public
    command: pnpm --filter=@glory-destiny-online-guide/prisma run start
    develop:
      watch:
        - action: sync
          path: ./packages/prisma/schema
          target: /app/packages/prisma/schema
        - action: sync
          path: ./packages/prisma/scripts/merge-prisma.ts
          target: /app/packages/prisma/scripts/merge-prisma.ts

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - prisma_generated:/app/packages/prisma/generated # 用同一個共享卷宗
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
      - prisma
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb?schema=public
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    develop:
      watch:
        - action: sync
          path: ./apps/api/src
          target: /app/apps/api/src

volumes:
  postgres_data:
  redis_data:
  prisma_generated: # 新增共享卷宗