FROM gdo-guide-base:latest AS api-dev
WORKDIR /app/apps/api
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install && npm install -g @nestjs/cli
EXPOSE 4000
CMD ["pnpm", "run", "dev"]