FROM node:20-alpine

WORKDIR /app
RUN npm install -g pnpm 
COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/api/package.json apps/api/
COPY packages/prisma/package.json packages/prisma/
RUN pnpm install --frozen-lockfile
COPY apps/api ./apps/api
COPY packages/prisma ./packages/prisma
EXPOSE 4000
CMD ["pnpm", "--filter=@glory-destiny-online-guide/api", "run", "start:dev"]